version: '3.8'

services:
  # Service pour créer les tables (s'exécute puis s'arrête)
  db_init:
    build:
      context: .
      dockerfile: Dockerfile
    command: python create_tables.py
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://mwinda:mwinda@postgres:5432/mwindaIdentity

  # Service pour l'application FastAPI
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8001:8001"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  # Service pour RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # Service pour PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: mwinda
      POSTGRES_PASSWORD: mwinda
      POSTGRES_DB: mwindaIdentity
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mwinda -d mwindaIdentity"]
      interval: 5s
      retries: 5
      timeout: 3s
