import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get('window');
const isTablet = width > 600;

export const COLORS = {
  primary: '#FEC109',
  dark: '#121212',
  light: '#FFFFFF',
  text: '#333333',
  lightText: '#666666',
  background: '#F8F9FA',
  cardBorder: '#E9ECEF',
  secondary: '#6C757D',
  accentBlue: '#0D6EFD',
  accentGreen: '#198754',
  accentRed: '#DC3545',
  accentPurple: '#6F42C1'
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingBottom: isTablet ? 40 : 30,
  },
  header: {
    paddingHorizontal: isTablet ? 40 : 25,
    paddingTop: isTablet ? 50 : 40,
    paddingBottom: isTablet ? 35 : 30,
    alignItems: 'center',
    backgroundColor: COLORS.light,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  logoBadge: {
    width: isTablet ? 60 : 50,
    height: isTablet ? 60 : 50,
    borderRadius: isTablet ? 30 : 25,
    backgroundColor: COLORS.dark,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  slogan: {
    fontSize: isTablet ? 26 : 22,
    fontWeight: '700',
    color: COLORS.dark,
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  subSlogan: {
    fontSize: isTablet ? 16 : 14,
    color: COLORS.secondary,
    textAlign: 'center',
    maxWidth: isTablet ? '70%' : '80%',
    lineHeight: isTablet ? 24 : 20,
  },
  servicesContainer: {
    paddingHorizontal: isTablet ? 30 : 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: isTablet ? 15 : 13,
    fontWeight: '600',
    color: COLORS.secondary,
    letterSpacing: 1.5,
    textAlign: 'center',
    marginBottom: 25,
    textTransform: 'uppercase',
  },
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: isTablet ? 'flex-start' : 'space-between',
    gap: isTablet ? '3%' : 0,
  },
  serviceCard: {
    width: isTablet ? '30%' : '48%',
    backgroundColor: COLORS.light,
    borderRadius: 12,
    padding: isTablet ? 24 : 18,
    marginBottom: isTablet ? 20 : 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    borderTopWidth: 3,
  },
  serviceIcon: {
    width: isTablet ? 48 : 40,
    height: isTablet ? 48 : 40,
    borderRadius: isTablet ? 24 : 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  serviceName: {
    fontSize: isTablet ? 18 : 16,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 8,
    textAlign: 'center',
  },
  serviceDescription: {
    fontSize: isTablet ? 14 : 12,
    color: COLORS.lightText,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: isTablet ? 21 : 18,
  },
  separator: {
    height: 1,
    width: '100%',
    backgroundColor: COLORS.cardBorder,
    marginBottom: 12,
  },
  ctaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ctaText: {
    fontSize: isTablet ? 14 : 12,
    fontWeight: '600',
    marginRight: 5,
  },
  loyaltyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.light,
    borderRadius: 12,
    padding: isTablet ? 24 : 18,
    marginHorizontal: isTablet ? 30 : 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  loyaltyContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  loyaltyIcon: {
    width: isTablet ? 44 : 36,
    height: isTablet ? 44 : 36,
    borderRadius: isTablet ? 22 : 18,
    backgroundColor: '#FFF9C4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  loyaltyTitle: {
    fontSize: isTablet ? 14 : 12,
    fontWeight: '600',
    color: COLORS.secondary,
    letterSpacing: 1,
    marginBottom: 2,
  },
  loyaltyPoints: {
    fontSize: isTablet ? 22 : 18,
    fontWeight: '700',
    color: COLORS.dark,
  },
});