import { StyleSheet } from "react-native";

const COLORS = {
  primary: '#FEC109',
  dark: '#121212',
  light: '#FFFFFF',
  text: '#333333',
  lightText: '#666666',
  background: '#F8F9FA',
  cardBorder: '#E9ECEF',
  secondary: '#6C757D',
  accentBlue: '#0D6EFD',
  accentGreen: '#198754'
};
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  scrollContainer: {
    paddingBottom: 30,
  },
  header: {
    paddingHorizontal: 25,
    paddingTop: 40,
    paddingBottom: 30,
    alignItems: 'center',
    backgroundColor: COLORS.light,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  logoBadge: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.dark,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  slogan: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.dark,
    textAlign: 'center',
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  subSlogan: {
    fontSize: 14,
    color: COLORS.secondary,
    textAlign: 'center',
    maxWidth: '80%',
    lineHeight: 20,
  },
  servicesContainer: {
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.secondary,
    letterSpacing: 1.5,
    textAlign: 'center',
    marginBottom: 25,
    textTransform: 'uppercase',
  },
  servicesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  serviceCard: {
    width: '48%',
    backgroundColor: COLORS.light,
    borderRadius: 10,
    padding: 18,
    marginBottom: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
    borderTopWidth: 0,
  },
  serviceIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 15,
  },
  serviceName: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.dark,
    marginBottom: 8,
    textAlign: 'center',
  },
  serviceDescription: {
    fontSize: 12,
    color: COLORS.lightText,
    textAlign: 'center',
    marginBottom: 15,
    lineHeight: 18,
  },
  separator: {
    height: 1,
    width: '100%',
    backgroundColor: COLORS.cardBorder,
    marginBottom: 12,
  },
  ctaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ctaText: {
    fontSize: 12,
    color: COLORS.primary,
   
    fontWeight: '600',
    marginRight: 5,
    
  },
  loyaltyCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.light,
    borderRadius: 12,
    padding: 18,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: COLORS.cardBorder,
  },
  loyaltyContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  loyaltyIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FFF9C4',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  loyaltyTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.secondary,
    letterSpacing: 1,
    marginBottom: 2,
  },
  loyaltyPoints: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.dark,
  },
});