import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9F9F9',
  },
  container1: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fec107',
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  image: {
    width: '80%',
    height: '70%',
    resizeMode: 'contain',
  },
  container2: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 30,
  },
  form: {
    backgroundColor: '#FFF',
    borderRadius: 20,
    padding: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
    marginBottom: 30,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#444',
    marginBottom: 8,
    marginLeft: 5,
  },
  input: {
    backgroundColor: '#F7F7F7',
    height: 50,
    borderRadius: 12,
    paddingHorizontal: 20,
    marginBottom: 20,
    fontSize: 16,
    color: '#333',
    borderWidth: 1,
    borderColor: '#EEE',
  },
  buttonContainer: {
    marginVertical: 20,
    alignItems: 'center',
  },
  activeButton: {
    backgroundColor: '#fec107',
    width: '100%',
    padding: 16,
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: '#fec107',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  activeText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#333',
    textAlign: 'center',
  },
  secondaryText: {
    fontSize: 16,
    color: '#666',
    textDecorationLine: 'underline',
  },
  linkText: {
    textAlign: 'center',
    color: '#fec107',
    fontWeight: '600',
    marginTop: 15,
  },
});

export default styles;