name: Bug
description: Bug report
title: "[tcf-XXX] "
labels: ["type:bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happens?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What should happen?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: Service
      options:
        - svc:tcf-user
        - svc:tcf-www
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:P0
        - prio:P1
        - prio:P2
    validations:
      required: true
