name: Feature
description: New feature request
title: "[TCF-XXX] "
labels: ["type:feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Goal
      description: What are we building and why?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      value: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true
  - type: dropdown
    id: service
    attributes:
      label: Service
      options:
        - svc:tcf-user

        - svc:tcf-www
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - prio:P0
        - prio:P1
        - prio:P2
    validations:
      required: true
